serviceName: demo-app01
project: default
namespace: argocd

k8sServer: cnoe-ref-impl

envList:
  dev:
    repo: dev
    path: "abc"
    namespace: demo-app01-dev
#   test:
#     repo: test
#     path: "abc"
#     namespace: demo-app01-test
