agentName: agent008
envName: dev
agentRuntimeName: agent008_dev
imageRepo: 229560443702.dkr.ecr.us-west-2.amazonaws.com
tag: latest
roleArn: arn:aws:iam::229560443702:role/service-role/AmazonBedrockAgentCoreRuntimeDefaultServiceRole
cloudWatchLogTailRoleArn: arn:aws:iam::229560443702:role/cnoe-refl-cw-logs-tail
agentRuntimeID: demoagent002_dev-P57qHb5iUO
region: us-west-2



environmentVariables:
  # OPENAI_API_SECRET: "/tenant001/agent001/api_key"
  # REGION: "us-west-2"

secrets:
  # - name: openapi_key
  #   vault:
  #     path: tenant004/awsagent001
  #     key: api_key
  #   awsSecretManager:
  #     key: "tenant004/awsagent001/api_key"
    
