agentName: sample
envName: dev
namespace: sample-dev

images:
  apiServerImage:
    repository: 229560443702.dkr.ecr.us-west-2.amazonaws.com/REPO_NAME
    tag: 0.0.1

apiServer:
  service:
    type: ClusterIP

studio:
  service:
    type: ClusterIP

postgres:
  external:
    enabled: false
    secretManager:
      enabled: false
      secretName: postgres-secret
      secretKey: connectionUrl

config:
  existingSecretName: langgraph-cloud-secrets